# Generated by Django 6.0.1 on 2026-01-26 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_orderitem_shipping_address_and_more"),
        ("products", "0002_alter_product_price"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
    ]
