# Generated by Django 6.0.1 on 2026-01-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_cartitem_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        # migrations.AlterUniqueTogether(
        #     name="cartitem",
        #     unique_together=None,
        # ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
